# .github/workflows/portable.yml（新建）
name: Build Portable

# env:
# TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }} 
# TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_PRIVATE_KEY_PASSWORD }}

on:
  workflow_dispatch:      # 手动触发
  push:
    tags: ['v*']         # 或者 tag 触发

jobs:
  build-portable:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [x86_64-pc-windows-msvc] # target: [x86_64-pc-windows-msvc, aarch64-pc-windows-msvc]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - uses: pnpm/action-setup@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - run: pnpm install
      - run: pnpm run prebuild
      - run: pnpm build
      - run: pnpm portable-fixed-webview2 ${{ matrix.target }}   # 或 pnpm portable

      - name: Upload Portable ZIP
        # uses: actions/upload-artifact@v4
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            name: Clash.Verge_portable_${{ matrix.target }}
            path: "*.zip"
