name: Build Portable

on:
  workflow_dispatch:
  push:
    tags: ['v*']
env:
  TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
  TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_PRIVATE_KEY_PASSWORD }}
    

jobs:
  build-portable:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - run: pnpm install

      # ⭐ 安装 Tauri 2.x CLI（关键修复）
      #- name: Install Tauri CLI
      #  run: pnpm add -g @tauri-apps/cli@latest

      - run: pnpm run prebuild

      # ⭐ portable 构建（现在不会报错）
      - name: Build Tauri Portable
        run: pnpm build

      - name: Fix WebView2
        run: pnpm portable

      - name: Upload Portable ZIP
        uses: actions/upload-artifact@v4
        with:
          name: Clash.Verge_portable
          path: src-tauri/target/release/bundle/portable/*.zip
